version: '3.4'
services:
  server:
    build:
      context: .
    image: server
    command: |
      -config /config
      -appname p2pdserver
      -e integration
      -migrate
    environment: 
      - P2PDSERVER_DATABASE_HOST=db
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
    volumes:
      - ./test/config:/config
  db:
    image: "postgres:12.2"
    command: |
      -c log_statement=all 
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/db.crt
      -c ssl_key_file=/var/lib/postgresql/db.key   
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=db
    volumes:
      - db-data:/var/lib/postgresql/data/ # persist data even if container shuts down
      - ./certs/db.crt:/var/lib/postgresql/db.crt
      - ./certs/db.key:/var/lib/postgresql/db.key   
volumes:
  db-data:
